<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="spring-ma.achievo.com" name="Default test" tests="10" failures="2" timestamp="23 Nov 2015 08:13:18 GMT" time="118.89" errors="0">
  <testcase name="test000login" time="13.508" classname="projects.ticket.testCases.ticketWeb.baShi">
    <failure type="java.lang.AssertionError" message="expected [333334] but found [333]">
      <![CDATA[java.lang.AssertionError: expected [333334] but found [333]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at test.autotest.core.UI.assertEquals(UI.java:86)
	at projects.ticket.testCases.ticketWeb.baShi.test000login(baShi.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- test000login -->
  <testcase name="test002login" time="0.001" classname="projects.ticket.testCases.ticketWeb.baShi"/>
  <testcase name="test003login" time="0.001" classname="projects.ticket.testCases.ticketWeb.baShi"/>
  <testcase name="test000login" time="10.997" classname="projects.ticket.testCases.ticketWeb.qiChe"/>
  <testcase name="test003login" time="0.001" classname="projects.ticket.testCases.ticketWeb.qiChe"/>
  <testcase name="test004login" time="0.001" classname="projects.ticket.testCases.ticketWeb.qiChe"/>
  <testcase name="test005login" time="20.725" classname="projects.ticket.testCases.ticketWeb.qiChe">
    <failure type="java.lang.AssertionError" message="Can not find the 登录输入框 element on the 登录页 page.">
      <![CDATA[java.lang.AssertionError: Can not find the 登录输入框 element on the 登录页 page.
	at org.testng.Assert.fail(Assert.java:94)
	at test.autotest.core.UI.waitDisplay(UI.java:154)
	at test.autotest.core.UI.waitDisplay(UI.java:137)
	at projects.ticket.frame.piaoWuWebTest.enterHomePage(piaoWuWebTest.java:15)
	at projects.ticket.testCases.ticketWeb.qiChe.test005login(qiChe.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- test005login -->
  <testcase name="test006login" time="0.0" classname="projects.ticket.testCases.ticketWeb.qiChe"/>
  <testcase name="test012editQiChePiaoJia" time="27.549" classname="projects.ticket.testCases.ticketWeb.qiChe"/>
  <testcase name="test000login" time="11.234" classname="projects.ticket.testCases.ticketWeb.cheDuiAndCheLiang"/>
</testsuite> <!-- Default test -->
